version: "3.7"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./static:/var/www/public/
    links:
      - backend
      - blog
    ports:
      - "80:80"

  backend:
    build: ./backend/
    environment:
      - PORT=3000

  blog:
    build: ./blog/
    environment:
      - PORT=3000
